requires 'Data::GUID';
requires 'DateTime';
requires 'DateTime::Format::MySQL';
requires 'DateTime::Format::W3CDTF';
requires 'Digest::SHA';
requires 'FindBin';
requires 'HTML::SocialMeta' => '0.72';
requires 'HTML::Strip';
requires 'JSON';
requires 'Modern::Perl';
requires 'Moo';
requires 'Path::Class';
requires 'Parallel::ForkManager';
requires 'Template';
requires 'Test::More';
requires 'Text::MultiMarkdown';
requires 'URI';
requires 'YAML';
