requires 'Capture::Tiny';
requires 'Data::GUID';
requires 'DateTime';
requires 'DateTime::Format::W3CDTF';
requires 'DBD::SQLite';
requires 'FindBin';
requires 'HTML::SocialMeta' => '0.72';
requires 'HTML::Strip';
requires 'JSON';
requires 'Moo';
requires 'List::Util' => '1.45';
requires 'LWP';
requires 'Path::Class';
requires 'Template';
requires 'Test::Warn';
requires 'Text::MultiMarkdown';
requires 'Text::Wrap';
requires 'URI';
requires 'YAML';
